"use strict";
/* NEXT LEVEL SUBS — single central product source for every page. */
(function(){
  if(window.__NLSCentralCatalogBooted)return;window.__NLSCentralCatalogBooted=true;
  const KEY="nls:central-catalog:v2",CART="streamHubCart",SIGNAL="nls:central-catalog-changed";
  const normalize=p=>{if(!p)return null;const media=Array.isArray(p.product_media)?p.product_media.filter(x=>x&&x.is_active!==false).sort((a,b)=>(a.display_order||0)-(b.display_order||0)):[];const role=r=>media.filter(x=>x.role===r);const primary=role("primary")[0]?.url||p.image_url||p.image||"";const logo=role("logo")[0]?.url||primary;const gallery=role("gallery").map(x=>x.url).filter(Boolean);const plans=(p.product_plans||[]).filter(x=>x&&x.is_available!==false).sort((a,b)=>(a.display_order||0)-(b.display_order||0));return {...p,image:primary,logo,images:[...new Set([primary,...gallery].filter(Boolean))],product_plans:plans,pricing:plans.map(x=>({id:x.id,name:x.name,duration:x.duration,price:Number(x.price||0),old_price:x.old_price==null?null:Number(x.old_price),currency:x.currency||p.currency||"BDT",popular:!!x.extra_data?.popular,discount:x.extra_data?.discount||""})),price:Number(p.price||plans[0]?.price||0)};};
  async function fetchCatalog(){const r=await fetch("/api/products?_nls_catalog="+Date.now(),{cache:"no-store"});if(!r.ok)throw Error(`Central catalog API ${r.status}`);const b=await r.json();return(b.products||[]).map(normalize).filter(Boolean)}
  const syncCart=list=>{try{const raw=localStorage.getItem(CART);if(!raw)return;const cart=JSON.parse(raw);if(!Array.isArray(cart))return;const bySlug=new Map(list.map(p=>[String(p.slug).toLowerCase(),p]));const next=cart.map(i=>{const p=bySlug.get(String(i.slug||i.product_slug||"").toLowerCase());if(!p)return i;const wanted=String(i.selectedPlan?.duration||i.duration||"").toLowerCase();const plan=p.product_plans.find(x=>String(x.duration||x.name||"").toLowerCase()===wanted)||p.product_plans[0];return {...i,name:p.name,slug:p.slug,product_slug:p.slug,image:p.image,price:Number(plan?.price??p.price),duration:plan?.duration||i.duration,selectedPlan:plan?{...plan,price:Number(plan.price||0)}:i.selectedPlan};});localStorage.setItem(CART,JSON.stringify(next));window.dispatchEvent(new CustomEvent("nextlevel:checkout-cart-updated",{detail:{cart:next}}));if(typeof window.renderOrderSummary==="function")window.renderOrderSummary();}catch(e){console.warn("NEXT LEVEL SUBS: cart central sync skipped",e)}};
  const publish=list=>{window.NLSCentralCatalog={products:list,getBySlug:s=>list.find(p=>p.slug===s),getById:id=>list.find(p=>p.id===id),getByName:n=>list.find(p=>String(p.name).toLowerCase()===String(n).toLowerCase())};window.NextLevelSubs=window.NextLevelSubs||{};window.NextLevelSubs.subscriptions=list;window.products=list;syncCart(list);window.dispatchEvent(new CustomEvent("nls:central-catalog-ready",{detail:{products:list}}));window.dispatchEvent(new CustomEvent("nextlevel:products-updated",{detail:{products:list}}));};
  async function refresh(){try{const list=await fetchCatalog();if(list.length){localStorage.setItem(KEY,JSON.stringify(list));publish(list);return true}}catch(e){console.warn("NEXT LEVEL SUBS: central catalog refresh failed",e)}return false}
  async function boot(){let list=[];try{list=await fetchCatalog();if(list.length)localStorage.setItem(KEY,JSON.stringify(list));}catch(e){try{list=JSON.parse(localStorage.getItem(KEY)||"[]")}catch{list=[]}if(!list.length&&window.__NLS_CENTRAL_PRODUCT__)list=[normalize(window.__NLS_CENTRAL_PRODUCT__)];console.warn("NEXT LEVEL SUBS: central catalog fallback",e)}if(list.length)publish(list);}
  if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",boot,{once:true});else boot();
  window.addEventListener("storage",e=>{if(e.key===SIGNAL)refresh();});
  window.addEventListener(SIGNAL,refresh);
  window.addEventListener("focus",()=>refresh());
  setInterval(()=>{if(document.visibilityState==="visible")refresh()},5000);
  window.NLSCentralCatalogRefresh=refresh;
})();
