"use strict";
const fs=require("fs");
const path=require("path");
const vm=require("vm");
const SITE={name:"NEXT LEVEL SUBS",domain:"https://www.nextlevelsubs.com",language:"en",logo:"/assets/logo.png"};
const aliases={netflix:"netflix-premium",duolingo:"doulingo","youtube-premium-nonrenewable":"youtube-premium-non-renewable"};
function slugify(v){return String(v==null?"":v).toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"");}
function escapeHTML(v){return String(v==null?"":v).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\"/g,"&quot;").replace(/'/g,"&#039;");}
function safeJSON(v){try{return JSON.stringify(v==null?null:v).replace(/</g,"\\u003c").replace(/>/g,"\\u003e").replace(/&/g,"\\u0026").replace(/\u2028/g,"\\u2028").replace(/\u2029/g,"\\u2029");}catch(_){return "null";}}
function loadProducts(){
 const file=path.join(__dirname,"..","js","details.js"),source=fs.readFileSync(file,"utf8");
 try{const loaded=require(file);if(Array.isArray(loaded)&&loaded.length)return loaded;if(loaded&&Array.isArray(loaded.products)&&loaded.products.length)return loaded.products;}catch(error){console.warn("details.js CommonJS load failed; using data-only fallback:",error&&error.message);}
 const marker=source.indexOf("const products"),start=source.indexOf("[",marker);if(marker<0||start<0)throw new Error("Product catalog declaration not found in js/details.js");
 let depth=0,quote=null,escaped=false,lineComment=false,blockComment=false,end=-1;
 for(let i=start;i<source.length;i++){const c=source[i],n=source[i+1];if(lineComment){if(c==="\n")lineComment=false;continue;}if(blockComment){if(c==="*"&&n==="/"){blockComment=false;i++;}continue;}if(quote){if(escaped){escaped=false;continue;}if(c==="\\"){escaped=true;continue;}if(c===quote)quote=null;continue;}if(c==="'"||c==='"'||c==='`'){quote=c;continue;}if(c==="/"&&n==="/"){lineComment=true;i++;continue;}if(c==="/"&&n==="*"){blockComment=true;i++;continue;}if(c==="[")depth++;else if(c==="]"){depth--;if(depth===0){end=i+1;break;}}}
 if(end<0)throw new Error("Could not find end of product catalog array");const products=vm.runInNewContext("("+source.slice(start,end)+")",Object.create(null),{timeout:3000});if(!Array.isArray(products))throw new Error("Extracted product catalog is not an array");return products;
}
function buildProductMap(list){const map=Object.create(null);for(const p of list){if(!p||typeof p!=="object"||!p.name)continue;const key=slugify(p.slug||p.name);if(key)map[key]=p;}return map;}
let products,productLoadError;try{products=buildProductMap(loadProducts());}catch(error){productLoadError=error;products=Object.create(null);console.error("PRODUCT CATALOG LOAD ERROR:",error&&error.stack?error.stack:error);}
let seoContent=Object.create(null);try{const seo=require(path.join(__dirname,"seo-content.js"));seoContent=seo&&typeof seo==="object"?seo:Object.create(null);}catch(error){console.warn("SEO content load failed:",error&&error.message);}
function resolveSlug(value){if(typeof value!=="string")return"";let slug=value.trim();try{slug=decodeURIComponent(slug);}catch(_){}slug=slugify(slug);if(products[slug])return slug;if(aliases[slug]&&products[aliases[slug]])return aliases[slug];for(const key of Object.keys(products))if(slugify(products[key].name)===slug)return key;return"";}
function getSlug(req){const q=req&&req.query&&typeof req.query.slug==="string"?req.query.slug:"",resolved=resolveSlug(q);if(resolved)return resolved;const pathname=String(req&&req.url||"").split("?")[0],m=pathname.match(/^\/(?:product|products)\/([^/]+)\/?$/i);return m?resolveSlug(m[1]):"";}
function absoluteURL(value){if(!value)return SITE.domain+SITE.logo;const v=String(value).trim();return/^https?:\/\//i.test(v)?v:SITE.domain+"/"+v.replace(/^\.\//,"").replace(/^\//,"");}
function categoryOf(p){if(p&&typeof p.category==="string"&&p.category.trim())return p.category.trim();if(p&&Array.isArray(p.categories))return p.categories.filter(Boolean).map(x=>String(x).replace(/-/g," ").replace(/\b\w/g,c=>c.toUpperCase())).join(", ");return"Digital Services";}
function pricingOf(p){return p&&Array.isArray(p.pricing)?p.pricing.filter(x=>x&&x.duration&&x.price!=null).map(x=>({duration:String(x.duration),price:Number(x.price),currency:x.currency||"BDT"})).filter(x=>Number.isFinite(x.price)):[];}
function seoOf(slug,p){const x=seoContent[slug];return x&&typeof x==="object"?{title:x.title||`${p.name} Subscription | ${SITE.name}`,description:x.description||`${p.description||"Premium subscription service"}. Get ${p.name} from ${SITE.name}.`}:{title:`${p.name} Subscription | ${SITE.name}`,description:`${p.description||"Premium subscription service"}. Get ${p.name} from ${SITE.name}.`};}
function schemaProduct(p,url,image,description){const s={"@context":"https://schema.org","@type":"Product","@id":url+"#product",name:p.name,description,image:[image],url,category:categoryOf(p),brand:{"@type":"Brand",name:SITE.name},seller:{"@type":"Organization",name:SITE.name,url:SITE.domain}};const rating=Number(p.rating),reviews=Number(p.reviews);if(Number.isFinite(rating)&&Number.isFinite(reviews)&&reviews>0)s.aggregateRating={"@type":"AggregateRating",ratingValue:rating,reviewCount:reviews};const pricing=pricingOf(p);if(pricing.length)s.offers=pricing.map(x=>({"@type":"Offer",url,priceCurrency:x.currency,price:x.price,name:`${p.name} - ${x.duration}`,availability:"https://schema.org/InStock",seller:{"@type":"Organization",name:SITE.name}}));return s;}
function notFound(res){res.statusCode=404;res.setHeader("Content-Type","text/html; charset=utf-8");res.setHeader("X-Robots-Tag","noindex, nofollow");return res.end(`<!doctype html><html><head><meta charset="utf-8"><title>Product Not Found</title></head><body><h1>Product Not Found</h1><a href="${SITE.domain}/">Return home</a></body></html>`);}
module.exports=function handler(req,res){try{
 if(!req||!res)throw new Error("Invalid Vercel request/response objects");
 if(req.method!=="GET"&&req.method!=="HEAD"){res.statusCode=405;res.setHeader("Allow","GET, HEAD");return res.end("Method Not Allowed");}
 if(productLoadError&&Object.keys(products).length===0)throw productLoadError;
 const slug=getSlug(req),p=slug?products[slug]:null;if(!p)return notFound(res);
 const url=`${SITE.domain}/product/${encodeURIComponent(slug)}`,image=absoluteURL(p.image||SITE.logo),seo=seoOf(slug,p),description=seo.description||`${p.name} subscription from ${SITE.name}`;
 res.statusCode=200;res.setHeader("Content-Type","text/html; charset=utf-8");res.setHeader("Content-Language",SITE.language);res.setHeader("X-Content-Type-Options","nosniff");res.setHeader("X-Robots-Tag","index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1");res.setHeader("Cache-Control","public, max-age=300, s-maxage=3600, stale-while-revalidate=86400");if(req.method==="HEAD")return res.end();
 const file=path.join(__dirname,"..","details.html");let html=fs.readFileSync(file,"utf8");
 const productSchema=schemaProduct(p,url,image,description),breadcrumbSchema={"@context":"https://schema.org","@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"Home",item:SITE.domain+"/"},{"@type":"ListItem",position:2,name:categoryOf(p),item:SITE.domain+"/"},{"@type":"ListItem",position:3,name:p.name,item:url}]};
 const bootstrap=`<base href="/">\n<script>(function(){var name=${JSON.stringify(p.name)},path=location.pathname;try{var u=new URL(location.href);if(!u.searchParams.get('name')){history.replaceState({nlsProduct:true},'',path+'?name='+encodeURIComponent(name));document.addEventListener('DOMContentLoaded',function(){setTimeout(function(){history.replaceState(null,'',path);},0);},{once:true});}}catch(e){}})();</script>`;
 html=html.replace(/<head>/i,`<head>${bootstrap}`);
 html=html.replace(/<title>[\s\S]*?<\/title>/i,`<title>${escapeHTML(seo.title)}</title>`);
 html=html.replace(/<meta name="description"[^>]*>/i,`<meta name="description" content="${escapeHTML(description)}">`);
 html=html.replace(/<link rel="canonical"[^>]*>/i,`<link rel="canonical" href="${escapeHTML(url)}">`);
 html=html.replace(/<meta property="og:title"[^>]*>/i,`<meta property="og:title" content="${escapeHTML(seo.title)}">`).replace(/<meta property="og:description"[^>]*>/i,`<meta property="og:description" content="${escapeHTML(description)}">`).replace(/<meta property="og:url"[^>]*>/i,`<meta property="og:url" content="${escapeHTML(url)}">`).replace(/<meta property="og:image"[^>]*>/i,`<meta property="og:image" content="${escapeHTML(image)}">`).replace(/<meta name="twitter:title"[^>]*>/i,`<meta name="twitter:title" content="${escapeHTML(seo.title)}">`).replace(/<meta name="twitter:description"[^>]*>/i,`<meta name="twitter:description" content="${escapeHTML(description)}">`).replace(/<meta name="twitter:image"[^>]*>/i,`<meta name="twitter:image" content="${escapeHTML(image)}">`);
 html=html.replace(/<\/head>/i,`<script type="application/ld+json">${safeJSON(productSchema)}</script><script type="application/ld+json">${safeJSON(breadcrumbSchema)}</script></head>`);
 return res.end(html);
 }catch(error){console.error("NEXT LEVEL SUBS product function error:",error&&error.stack?error.stack:error);res.statusCode=500;res.setHeader("Content-Type","application/json; charset=utf-8");return res.end(JSON.stringify({error:"Internal Server Error",message:error&&error.message?error.message:"Unknown error"}));}};
